app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/ollama/ollama
            tag: 0.3.5
    ui:
      containers:
        main:
          image:
            repository: ghcr.io/open-webui/open-webui
            tag: latest
          env:
            OLLAMA_BASE_URL: http://ollama:11434
  service:
    main:
      ports:
        http:
          port: 11434
          protocol: HTTP
    ui:
      controller: ui
      ports:
        http:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: ollama.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: ai.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: ui
                port: http
      tls:
        - hosts:
            - ollama.eaglepass.io
            - ai.eaglepass.io
          secretName: ollama-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /root/.ollama
