#!/bin/bash

# Encode 1password-credentials.json
base64 /tmp/1password-credentials > /tmp/1password-credentials_encoded

# Encode onepassword-token
base64 /tmp/onepassword-token > /tmp/onepassword-token_encoded

# Create Kubernetes secret for 1password-credentials
kubectl create secret generic op-credentials --from-file=/tmp/1password-credentials_encoded -n global-secrets

# Create Kubernetes secret for onepassword-token
kubectl create secret generic op-token --from-file=/tmp/onepassword-token_encoded -n global-secrets

echo "Secrets have been created successfully."
